# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Code_now\ViAnalyser\vistart.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Startup(object):
    def setupUi(self, Startup):
        Startup.setObjectName("Startup")
        Startup.resize(704, 417)
        self.centralwidget = QtWidgets.QWidget(Startup)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.btn_sm = QtWidgets.QPushButton(self.groupBox)
        self.btn_sm.setGeometry(QtCore.QRect(60, 150, 93, 28))
        self.btn_sm.setObjectName("btn_sm")
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.btn_mm = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_mm.setGeometry(QtCore.QRect(70, 150, 93, 28))
        self.btn_mm.setObjectName("btn_mm")
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.btn_vm = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_vm.setGeometry(QtCore.QRect(60, 150, 93, 28))
        self.btn_vm.setObjectName("btn_vm")
        self.horizontalLayout.addWidget(self.groupBox_3)
        Startup.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Startup)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 704, 26))
        self.menubar.setObjectName("menubar")
        Startup.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Startup)
        self.statusbar.setObjectName("statusbar")
        Startup.setStatusBar(self.statusbar)

        self.retranslateUi(Startup)
        QtCore.QMetaObject.connectSlotsByName(Startup)

    def retranslateUi(self, Startup):
        _translate = QtCore.QCoreApplication.translate
        Startup.setWindowTitle(_translate("Startup", "ViAnalyser"))
        self.btn_sm.setText(_translate("Startup", "SingleMode"))
        self.btn_mm.setText(_translate("Startup", "MultiMode"))
        self.btn_vm.setText(_translate("Startup", "VideoMode"))
